services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
#    environment:
#      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/var/www/
    restart: unless-stopped
    depends_on:
        - db
        - db_test

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - app
      - db
      - db_test
    restart: unless-stopped

  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    build:
      context: ./mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql:rw
    restart: unless-stopped

  db_test:
    container_name: ${COMPOSE_PROJECT_NAME}_test_db
    build:
      context: ./mysql
    ports:
      - ${DB_TEST_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}_test
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_test_data:/var/lib/mysql:rw
    restart: unless-stopped

volumes:
  db_data:
  db_test_data:

